apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-success-rate
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(rate(http_server_requests_seconds_count{
              namespace="jetstay",
              status!~"5.."
            }[2m]))
            /
            sum(rate(http_server_requests_seconds_count{
              namespace="jetstay"
            }[2m]))