apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: 1h
  secretStoreRef: 
    name: jetstay-secret-store
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef: 
        key: jetstay/backend
        property: SPRING_DATASOURCE_PASSWORD

# ExternalSecret tên backend-secret
# → đọc secret thật từ jetstay-secret-store
# → lấy key jetstay/backend
# → lấy property SPRING_DATASOURCE_PASSWORD
# → tạo Kubernetes Secret tên backend-secret