apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: jetstay

# ExternalSecret tên backend-secret
# → đọc secret thật từ jetstay-secret-store
# → lấy key jetstay/backend
# → lấy property SPRING_DATASOURCE_PASSWORD
# → tạo Kubernetes Secret tên backend-secret