apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Runs after Wave 1 is finished!
spec:
  project: default
  source:
    repoURL: https://github.io
    chart: kube-prometheus-stack
    targetRevision: 86.2.2
    helm:
      releaseName: kube-prometheus-stack
      values: |
        # This stops Helm from trying to install CRDs again
        crds:
          enabled: false 
        grafana:
          enabled: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - ServerSideApply=trueManagedFieldsOnly=true