apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" #Runs First!
spec: feniks@DESKTOP-VCMR1O8:/mnt/g/de_space/xbrain/jetstay-gitops$ kubectl -n argocd get applications
NAME                SYNC STATUS   HEALTH STATUS
jetstay-backend     Synced        Healthy
jetstay-frontend    Synced        Healthy
jetstay-mysql       Synced        Healthy
jetstay-namespace   Synced        Healthy
jetstay-root        Synced        Healthy
monitoring          OutOfSync     Healthy
  project: default
  source:
    repoURL: https://github.io
    chart: prometheus-operator-crds
    targetRevision: 17.0.2 # Use a version matching your stack
  destination:
    server: https://default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true