apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
  namespace: demo
  labels:
    app: api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/feniksxshi/todoapp-python:v5-bad
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v5-bad"
            - name: ERROR_RATE
              value: "1"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20

  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: api-success-rate
        - setWeight: 50
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: api-success-rate
        - setWeight: 100
